### ISSUE TITLE
GHC 9.0.2 regression: Ambiguous occurrence ‘throwM’

### ISSUE THREAD

**Issue by shaddybaddah** [raspberrypi/bookworm-feedback#403]
I've built git-annex-standalone (see https://neuro.debian.net/) for armhf under Debian 11 (bullseye) with success. I believe this was using GHC 8.8.4-2.

When I try to build for armhf via Raspbian, but not under Debian for x86_64, I encounter this error:

    Utility/Url.hs:270:30: error:
        Ambiguous occurrence ‘throwM’
        It could refer to
           either ‘Common.throwM’,
                  imported from ‘Common’ at Utility/Url.hs:46:1-13
                  (and originally defined in ‘Control.Monad.Catch’)
               or ‘Control.Monad.Trans.Resource.throwM’,
                  imported from ‘Control.Monad.Trans.Resource’ at Utility/Url.hs:63:1-35
                  (and originally defined in ‘exceptions-0.10.4:Control.Monad.Catch’)
        |
    270 |                         _ -    throwM he
        |                              ^^^^^^

As above, this builds fine using the "same" GHC 9.0.2 under Debian for x86_64.

I will try to isolate this issue at some point. But I want it recorded here first, in case someone has already encountered this and worked through it.

**Comment by lurch** [comment]
This sounds like an upstream bug in Debian or GHC or git-annex-standalone, rather than something specific to Raspberry Pi OS, so closing.
